name: openai-auth-action
description: Authenticate to the OpenAI API with the workload identity federation.
inputs:
  audience:
    description: Audience of GitHub Actions OIDC token
    required: true
  identity-provider-id:
    description: OpenAI workload identity provider ID
    required: true
  service-account-id:
    description: OpenAI service account ID
    required: true
outputs:
  token:
    description: A short-lived token for OpenAI
runs:
  using: 'node24'
  main: 'dist/index.js'
